{% set name = "conda-pack" %}
{% set version = "0.7.0" %}
{% set sha256 = "cac32975588095d5eefdf34bec48b22f2c33d304e12f24076952da96b1133b5f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-pack = conda_pack.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python >=3.6

test:
  commands:
    - conda-pack --help
  imports:
    - conda_pack

about:
  home: https://conda.github.io/conda-pack/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package conda environments for redistribution
  description: |
    ``conda-pack`` is a command line tool for creating relocatable conda
    environments. This is useful for deploying code in a consistent environment,
    potentially in a location where python/conda isn't already installed.
  doc_url: https://conda.github.io/conda-pack/
  dev_url: https://github.com/conda/conda-pack

extra:
  recipe-maintainers:
    - jcrist
    - mcg1969
    - dbast
